### ISSUE TITLE
Not Showing More than one classes in a specific schedule

### ISSUE THREAD

**Issue by zuizihad** [shunjid/routine-explorer#1]
There is a bug remaining in this application I guess. If there is more than one class in a particular schedule then the application is showing just one class code. Can you please fix this problem?

**Comment by shunjid** [comment]
This is happening probably not concatenating classes in **[b444737](https://github.com/shunjid/routine-explorer/commit/b444737dae5e9027c595d0b1ca1dfae8f2889aad)**

Thanks for letting me know this issue. Hopefully, I'll fix it soon @zuizihad

**Comment by shunjid** [comment]
![Issue](https://user-images.githubusercontent.com/29749035/58264760-3a6d6d00-7da0-11e9-9487-5f27fb5b9d8a.png)

@zuizihad Closing this issue due to bug fixes. Thank you again for your contribution.
